server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: user-service # 路由标识，必须唯一
          uri: lb://userservice # 路由的目标地址，lb代表根据服务名负载均衡，后面跟服务名称
          # uri: http://localhost:8082/ # 路由的目标地址，http代表固定地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters:
            - AddRequestHeader=Str,Hello word!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**